Repository armory/docs, pull requests merged in 2020-12, with the labels that each got.

#321 feat(docs): adding cloudwatch config and example
  content/en/docs/armory-admin/kayenta-configure.md
  content/en/docs/cloud-resources/resources-aws.md
  content/en/docs/spinnaker-user-guides/canary/StaticBaselineJudge.md
  content/en/docs/spinnaker-user-guides/canary/_index.md
  content/en/docs/spinnaker-user-guides/canary/kayenta-canary-cloudwatch.md
  content/en/docs/spinnaker-user-guides/canary/kayenta-canary-dynatrace.md
  content/en/docs/spinnaker-user-guides/canary/kayenta-canary-use.md
  content/en/includes/user-guide/canary/config-kayenta-frag.md
  static/images/user-guides/canary/cloudwatch/canary_cloudwatch_metrics.png
  static/images/user-guides/canary/cloudwatch/canary_config_cloudwatch.png
  static/images/user-guides/canary/cloudwatch/canary_config_cloudwatch_query.png
  static/images/user-guides/canary/cloudwatch/canary_report_cloudwatch.png
  static/images/user-guides/canary/cloudwatch/canary_stage_cloudwatch.png
Labels: release-2.23.1

#357 docs(seo): configure sitemap plugin in netlify.toml
  netlify.toml
Labels: Improvement

#358 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#361 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#360 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#359 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#363 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#370 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#369 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#372 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#373 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#377 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#376 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#375 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#379 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#380 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#381 chore(release): Autobump agent version
  config.toml
Labels: auto merged

#382 chore(release): Autobump agent version
  config.toml
Labels: auto merged
