Repository armory/docs, pull requests merged in 2023-01, with the labels that each got.

#1758 Update(dinghy-enable): Multi Branch Toggle
  content/en/continuous-deployment/armory-admin/dinghy-enable.md
  content/en/includes/note-github-branch-name.md
Labels: release-2.28.2

#1785 chore(release): add release notes for 2.28.2
  content/en/continuous-deployment/release-notes/release-definitions.md
  content/en/continuous-deployment/release-notes/rn-armory-spinnaker/armoryspinnaker_v2-28-2.md
  content/en/includes/known-issues/ki-empty-roles.md
  payload.json
Labels: releaseNotesUpdate, 2.28.2

#1793 chore(release): add release notes for 2.27.5
  content/en/continuous-deployment/release-notes/rn-armory-spinnaker/armoryspinnaker_v2-27-5.md
  payload.json
Labels: releaseNotesUpdate, 2.27.5

#1802 chore(release): add release notes for 2.27.6-rc1
  content/en/continuous-deployment/release-notes/rn-prerelease-armory-spinnaker/armoryspinnaker_v2-27-6-rc1.md
  payload.json
Labels: releaseNotesUpdate, automerge, 2.27.6-rc1

#1805 chore(release): add release notes for 2.28.3-rc2
  content/en/continuous-deployment/release-notes/rn-prerelease-armory-spinnaker/armoryspinnaker_v2-28-3-rc2.md
  payload.json
Labels: releaseNotesUpdate, automerge, 2.28.3-rc2

#1806 chore(release): add release notes for 2.27.6-rc2
  README.md
  content/en/continuous-deployment/release-notes/rn-prerelease-armory-spinnaker/armoryspinnaker_v2-27-6-rc2.md
  payload.json
Labels: releaseNotesUpdate, automerge, 2.27.6-rc2

#1801 chore(release): add release notes for 2.28.3-rc1
  content/en/continuous-deployment/release-notes/rn-prerelease-armory-spinnaker/armoryspinnaker_v2-28-3-rc1.md
  payload.json
Labels: releaseNotesUpdate, automerge, 2.28.3-rc1

#1834 chore(release): add release notes for 2.28.3
  content/en/continuous-deployment/release-notes/rn-armory-spinnaker/armoryspinnaker_v2-28-3.md
  payload.json
Labels: releaseNotesUpdate, 2.28.3

#1839 chore(release): add release notes for 2.27.6
  content/en/continuous-deployment/release-notes/rn-armory-spinnaker/armoryspinnaker_v2-27-6.md
  payload.json
Labels: releaseNotesUpdate, 2.27.6
